services:
  db:
    image: postgres:14-alpine
    container_name: postgres        
    networks:
      - compose-bridge
    environment:
      POSTGRES_DB: preco_justo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
      
  app:
    image: marcussalviano/preco-justo-teste:1.0
    container_name: preco-justo-teste    
    networks:
      - compose-bridge
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_NAME=preco_justo_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

    

networks:
  compose-bridge:
    driver: bridge
